[package]
name = "versio"
version = "0.1.0"
authors = ["Charlie Ozinga <ozchaz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
git2 = "0.12"
glob = "0.3"
yaml-rust = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
regex = "1.3"
version-compare = "0.0.10"
