[package]
name = "versio"
version = "0.1.0"
authors = ["Charlie Ozinga <ozchaz@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
git2 = "0.12"
# until the next version with updated deps is published
github-gql-rs = { version = "0.0.1", path = "../github-rs/github-gql-rs" }
glob = "0.3"
hyper = "0.12.27"
yaml-rust = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
regex = "1.3"
xmlparser = "0.13"

[lib]
name = "versio"
path = "src/lib.rs"

[[bin]]
name = "versio"
path = "src/main.rs"
doc = false
