name: 'check-cargo'
description: 'Check a project with cargo'
author: 'Charlie Ozinga <ozchaz@gmail.com>'
branding:
  icon: play-circle
  color: black
inputs:
  root:
    description: The root of a cargo project

outputs: {}

runs:
  using: 'composite'
  default:
    run:
      working-directory: ${{ inputs.root }}
  steps:
    - name: Get cargo
      uses: ./.github/actions/get-cargo
      with:
        root: ${{ inputs.root }}
    - name: Check structure
      run: cargo clippy
    - name: Check format
      run: cargo +nightly fmt -- --check
    - name: Check tests
      run: cargo test
