key: get-cargo-minimal
value:
  - name: Get cargo stable
    uses: actions-rs/toolchain@v1
    with:
      toolchain: stable
  - name: Cache cargo
    uses: actions/cache@v1
    with:
      path: |
        ~/.cargo/registry
        ~/.cargo/git
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
