key: job-versio-checks
value:
  runs-on: ubuntu-latest
  if: "!contains(github.event.head_commit.message, 'skip ci')"
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - SNIPPET_check-versio
