key: job-cargo-checks
value:
  needs: project-matrixes
  runs-on: ubuntu-latest
  strategy:
    matrix: ${{ fromJson(needs.project-matrixes.outputs.cargo-matrix) }}
  if: "!contains(github.event.head_commit.message, 'skip ci')"
  defaults:
    run:
      working-directory: ${{ matrix.root }}
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - SNIPPET_check-cargo
