---
name: pr
on:
  - pull_request
env:
  RUSTFLAGS: '-D warnings'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cargo-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache cargo and target
      uses: actions/cache@v1
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Get cargo stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Get cargo nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
    - name: Check structure
      run: cargo clippy
    - name: Check format
      run: cargo +nightly fmt -- --check
    - name: Check tests
      run: cargo test

  versio-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get versio
      uses: chaaz/versio-actions-install@v1
    - name: Fetch history
      run: git fetch --unshallow
    - name: Check projects
      run: versio check
    - name: Print changes
      run: versio plan
