---
name: pr
on:
  - workflow_dispatch  # pull_request
env:
  RUSTFLAGS: '-D warnings'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  project-matrixes:
    runs-on: ubuntu-latest
    outputs:
      cargo-matrix: steps.set-matrixes.output.cargo-matrix
      all-matrix: steps.set-matrixes.output.all-matrix
    steps: 
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Set matrixes, id: set-matrixes, uses: ./.github/actions/matrix }

  versio-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Versio checks, uses: ./.github/actions/check-versio }

  cargo-checks:
    needs: project-matrixes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.project-matrixes.outputs.cargo-matrix) }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    defaults:
      run:
        working-directory: ${{ matrix.root }}
    steps:
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Cargo checks, uses: ./.github/actions/check-cargo, with: { root: '${{ matrix.root }}' } }
