---
name: release
on:
  - workflow_dispatch
env:
  RUSTFLAGS: '-D warnings'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  project-matrixes:
    runs-on: ubuntu-latest
    outputs: ${{ fromJson(steps.set-matrixes.output.matrixes) }}
    steps: 
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Set matrixes, id: set-matrixes, uses: ./.github/actions/matrix }

  versio-checks:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Versio checks, uses: ./.github/actions/check-versio }

  cargo-checks:
    needs: project-matrixes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.project-matrixes.outputs.cargo-matrix) }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    defaults:
      run:
        working-directory: ${{ matrix.root }}
    steps:
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Cargo checks, uses: ./.github/actions/check-cargo, with: { root: '${{ matrix.root }}' } }

  versio-release:
    needs:
      - cargo-checks
      - versio-checks
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Generate release
      run: versio release

  cargo-post:
    needs: 
      - project-matrixes
      - versio-release
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.project-matrixes.outputs.cargo-matrix)}}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    defaults:
      run:
        working-directory: ${{ matrix.root }}
    steps:
    - { name: Checkout code, uses: actions/checkout@v2 }
    - { name: Get cargo, uses: ./.github/actions/get-cargo, with: { root: '${{ matrix.root }}' }}
    - name: Login to crates.io
      run: cargo login ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - name: Publish to crates.io
      run: cargo publish
